### ISSUE TITLE
Add “create” action on CLI

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress-cli#1]
cli package with node.

one install should do:
1. fork repository: greenpress-pm2
2. git clone all sub-modules.
3. initiate data with the existing scripts.
4. ask the email and password, blog name and description, to initiate data with valid populated data.
5. explain scripts to run local environment and production.

**Comment by krishnanunnir** [comment]
Hi, clearing up on few implementation doubt
1. By forking do you mean like creating a local repo of greenpress-pm2 
2. Can you explain the points 3 and 4 a bit more?

**Comment by krishnanunnir** [comment]
Few more doubts, wouldn't it be better to move greenpress-pm2/helpers to this repo?
Also using commands like 'execSync', wouldn't it be a problem for cross platform support?

**Comment by davidmeirlevy** [comment]
1. yes. I supposed to create a fork so users can commit their own changes into their own repos, but still rebase from the original.
2.
about 3)  `greenpress-pm2` has dev script to initiate stub data in the database, for the local environment.
It'll be great to run it for the user.
about 4) the "initiate data" is currently set a default user such as "test@test.com". It can be nice to ask the user his initial email, password, and blog name for the basic blog configurations.

3. When I wrote `greenpress-pm2`, it was the only solution to run greenpress, so I put it all there, but it's a nice idea to relocate parts.
That said, most of the helpers are needed to run `greenpress-pm2` directly on production environment (probably will run without this CLI tool), so those functions should stay there.
Also, this CLI was meant to create not just a "pm2" environment.
In the future, we want this CLI to ask the user if we like a local "docker-compose" "kubernetes" or "pm2" environment, and will create the local environment accordingly.

**Comment by davidmeirlevy** [comment]
Closing..  another "create" action will be defined.
