### ISSUE TITLE
[ Bug ] Missing commands renders version's output twice if version output is split (not consistent)

### ISSUE THREAD

**Issue by drorrose** [greenpress/greenpress-cli#14]
![split_version_output2](https://user-images.githubusercontent.com/46942510/90124756-976c8e80-dd69-11ea-9112-8a1ce177636a.png)

![split_version_output1](https://user-images.githubusercontent.com/46942510/90124752-95a2cb00-dd69-11ea-956f-c7529b51157d.png)

**Comment by davidmeirlevy** [comment]
@drorrose is that done?

**Comment by drorrose** [comment]
@davidmeirlevy yes, closing it.
