### ISSUE TITLE
Create application

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress-cli#3]
the command `greenpress create APPNAME` should:
1. create a folder named APPNAME.
2. copy the files from repo greenpress/greenpress.
3. run `npm install` and then `npm run dev`
4. wait until DB is up (can check with "pm2 ls" for running services) and run `npm run populate-db`
5. add a "welcome" note to console with basic instructions.

**Comment by drorrose** [comment]
`greenpress create [name] [type] [altFront] [mode]` does the following:
1. clones greenpress repo (greenpress/greenpress-pm2 based on "type") into "name" folder.
2. if "altFront" not set in command line, asks users whether he would like to switch default blog frontend with their own. Switches frontend if needed.
3. if "mode" is different than "dev", rename origin to gp
4. run `npm install` in "name" directory
5. displays a "welcome" not to console with basic instructions
