### ISSUE TITLE
[enhancement] Running application locally using docker & docker-compose

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress-cli#36]
In order to make the installation and initialization scripts more robust, it's time to implement all-the-way docker encapsulation for all OSs, and not just for windows.

Docker and Docker-Compose should be the default way to install and run the application locally, to avoid any case of OS, node, DBs, compilers conflicts.

**Comment by adityaarakeri** [comment]
I can take a look at this, assign the issue to me.

**Comment by logesr** [comment]
I can take up if it is still up for grabs!

**Comment by adityaarakeri** [comment]
go ahead, i am currently working on some other task

**Comment by davidmeirlevy** [comment]
@drorrose please use the help of the wonderful people here 🎉 

we already have an initial script to run the platform inside docker, with several different configuration cases, and the idea is to improve it to a level of 100% work without any obstacles, in all OSs, and to manage all CLI operations inside the docker (create, upgrade, service create, start / start dev, etc..)
