### ISSUE TITLE
[Enhancement] Add ability to work on local drafts service

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress-cli#38]
- [ ] on start application, add the ability to use the local flag also for drafts service.
- [ ] on upgrade - make sure drafts service is added to an upgraded app that didn't have it before.

**Comment by davidmeirlevy** [comment]
@drorrose i don't think it's a closed issues.
How is the upgrade will react for apps that don't have drafts service in them?

**Comment by drorrose** [comment]
The code works as follows:
1. Get remote dependencies
2. Get local dependencies
3. Iterate over remote dependencies and compare to local

Based on that, I assume it should just display that the versions are not similar, and prompt a question to the user if it should be added. I will test it later today to make sure it behaves as I expect.

**Comment by davidmeirlevy** [comment]
Ok. Just make sure that older versions without the drafts service will get the drafts.

**Comment by drorrose** [comment]
@davidmeirlevy 
Checked that, it works as expected. I'm closing this issue.
