### ISSUE TITLE
Add  a restart service command

### ISSUE THREAD

**Issue by or-yam** [greenpress/greenpress-cli#52]
Sometimes while working on a specific service we need to refresh in order to check the changes. 
It is faster to refresh only the service insted the whole project (greenpress stop, greenpress start dev) 
Adding a refresh service  command  will be nice to have. 

For example : `greenpress refresh admin` will execute : `docker exec greenpress_greenpress_1 pm2 restart admin`

**Comment by davidmeirlevy** [comment]
probably we should use "restart" instead of "refresh".

**Comment by or-yam** [comment]
I agree . "restart"  is better .

**Comment by drorrose** [comment]
@davidmeirlevy @or-yam 
I would change the usage. 
I would add it to the options of "greenpress service", so the usage will be "greenpress service restart <services_names>"

What do you think about it?

**Comment by davidmeirlevy** [comment]
@drorrose great!
