### ISSUE TITLE
Add "please wait" or somsthing like this after "Initializing Greenpress.." in the command "greenpress start"

### ISSUE THREAD

**Issue by AviadSofer** [greenpress/greenpress-cli#53]

**Comment by davidmeirlevy** [comment]
@drorrose @itays123 @or-yam @sliron1989 what do you say?

**Comment by or-yam** [comment]
Good idea 💡

**Comment by itays123** [comment]
I think 'doing our magic...' would do the trick

**Comment by davidmeirlevy** [comment]
> I think 'doing our magic...' would do the trick

It's not clear enough :)

**Comment by itays123** [comment]
> It's not clear enough :)

How about 'You can make a cup of coffee...' or something like this?

**Comment by davidmeirlevy** [comment]
I think we can do percentage of progress.
We already read the logs to find out if the app is up.
We can try to find more data in the logs that consider to be steps on the way..
For example: each backend service that is up can equal to +5%.
The content service is 10%
The admin panel is around 20%.
The front-blog is 50%, and so on.

What do you say?

**Comment by itays123** [comment]
> For example: each backend service that is up can equal to +5%.
> The content service is 10%
> The admin panel is around 20%.
> The front-blog is 50%, and so on.

Sounds reasonable, although it needs to be considered when adding new backend services. There should be a `services.json` file somewhere detailing the "weight" of each project for ease of modifying. 

In addition, the mongodb database has to have its own weight, I suggest 20%

**Comment by drorrose** [comment]
Seems like too much work just for nicer visibility. Reading the logs to such precision will require using a lot more calls to execSync. I think that a message coupled with a simple spinner or even progress bar that is not as precise (reads in large intervals, searching the latest massage and displays progress based on that) might do the trick.

About the progress bar suggestion - we know the loading process, so we can make an object that maps the service message to the progress percentage.

**Comment by or-yam** [comment]
Maybe instead of percentage ,tell the user what is happening with a loading animation next to it. Something like:
Building admin panel ( -\|/-)

**Comment by davidmeirlevy** [comment]
> About the progress bar suggestion - we know the loading process, so we can make an object that maps the service message to the progress percentage.

I believe it's doable.

> Building admin panel ( -\|/-)

They are all done simultaneously.

**Comment by drorrose** [comment]
So to summarize:
1. A wait message "please wait while Greenpress is starting - might take a couple of minutes" or something of that sort
2. A progress bar that is looking for specific strings in the log and moves according to the latest one found
3. Before successful finish message is being promoted, move the progress bar to 100% (if start up failed, keep progress bar at latest state)

What do you say?

**Comment by itays123** [comment]
> 1. A wait message "please wait while Greenpress is starting - might take a couple of minutes" or something of that sort

In my opinion the wait message should be "please wait while greenpress is starting.... Go make yourself a cup of coffee"

**Comment by drorrose** [comment]
@davidmeirlevy @or-yam @sliron1989 @itays123 
Do we have any consensus about it?
A crude progress bar and a sentence? If so, what is the final sentence that we would like to display?

**Comment by davidmeirlevy** [comment]
Take something nice from Itay's suggestions. :)
